import os
import tempfile
import subprocess

from cerebrum.tool.base import BaseTool


class CodeTestRunner(BaseTool):
    def __init__(self):
        super().__init__()
        self.timeout: float = 1.0

    def run(self, params) -> str:
        try:
            header = params["header"]
            code = params["code"]
            tests = params["tests"]
        except KeyError as e:
            return f"CodeTestRunner error: missing required parameter {e!r}"

        temp_dir = tempfile.mkdtemp(prefix="code_test_runner_")
        script_path = os.path.join(temp_dir, "run_tests.py")

        script_content = (
            "# Auto-generated by CodeTestRunner\n"
            "# --- Header code ---\n"
            f"{header}\n"
            "# --- User code ---\n"
            f"{code}\n"
            "# --- Test code ---\n"
            f"{tests}\n"
        )

        try:
            with open(script_path, "w", encoding="utf-8") as f:
                f.write(script_content)
        except Exception as e:
            return f"CodeTestRunner error: failed to write temp script: {e!r}"

        try:
            completed = subprocess.run(
                ["python", script_path],
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                timeout=self.timeout,
            )
            status = "success" if completed.returncode == 0 else "failure"
            stderr = completed.stderr or ""

            return {
                "status": status,
                "stderr": stderr,
            }

        except subprocess.TimeoutExpired as e:
            stderr = e.stderr or ""
            return {
                "status": "timeout",
                "stderr": stderr,
            }
        except Exception as e:
            return f"CodeTestRunner internal error during execution: {e!r}"

    def get_tool_call_format(self):
        tool_call_format = {
            "type": "function",
            "function": {
                "name": "code/code_test_runner",
                "description": (
                    "Execute Python code composed of three parts: "
                    "`prompt` (required imports and headers), `code` (the proposed solution), "
                    "and `tests` (assert-based test cases). "
                    "All three parts are combined into a single Python file and run "
                    "in an isolated subprocess. Returns execution status, exit code, "
                    "stdout and stderr."
                ),
                "parameters": {
                    "type": "object",
                    "properties": {
                        "header": {
                            "type": "string",
                            "description": (
                                "Python code that MUST appear at the top of the file. "
                                "Typically contains importsnor required headers. "
                            ),
                        },
                        "code": {
                            "type": "string",
                            "description": (
                                "The FULL solution code to be tested. "
                                "Must be valid Python code."
                            ),
                        },
                        "tests": {
                            "type": "string",
                            "description": (
                                "Assert-based Python tests that directly call the function"
                                "These tests run in the same file and must not import the solution from another module."
                            ),
                        },
                    },
                    "required": ["header", "code", "tests"],
                },
            },
        }
        return tool_call_format

