import os
import re
import tempfile
import subprocess
from typing import Optional

from cerebrum.tool.base import BaseTool

class CodeTestRunner(BaseTool):
    """
    CodeTestRunner Tool

    Execute user-provided Python code together with test code
    in an isolated subprocess and return the results.

    Expected params:
        code:   str - Python source code (functions/classes, etc.)
        tests:  str - Python test code (asserts or print-based checks)
        timeout: Optional[float] - execution timeout in seconds (default: 5.0)
    """

    def __init__(self):
        super().__init__()

        #print("\n" + "-" * 40 + "\n")
        #print("CodeTestRunner tool initialized")

        # Default timeout in seconds for test execution
        self.default_timeout: float = 5.0
        self._escape_pattern = re.compile(r"\\[nrt'\"\\]")

    def run(self, params) -> str:
        """
        Run the given code and tests in a temporary Python script.

        The tool:
        - Writes `code` and `tests` into a temporary file
        - Executes the file in a subprocess with a timeout
        - Captures stdout, stderr, and exit code
        - Returns a formatted string with the results

        Args:
            params: dict with keys:
                - "code": str, required
                - "tests": str, required
                - "timeout": float, optional

        Returns:
            A single string summarizing status, exit code, stdout, and stderr.
        """
        # Extract parameters
        try:
            code = params["code"]
            tests = params["tests"]
        except KeyError as e:
            return f"CodeTestRunner error: missing required parameter {e!r}"

        code = self._normalize_code_string(code)
        tests = self._normalize_code_string(tests)

        # breakpoint()

        timeout = params.get("timeout", self.default_timeout)

        # Create a temporary directory and script file
        temp_dir = tempfile.mkdtemp(prefix="code_test_runner_")
        script_path = os.path.join(temp_dir, "run_tests.py")

        # Build the combined script:
        # - user code first
        # - then test code that uses the definitions above
        script_content = (
            "# Auto-generated by CodeTestRunner\n"
            "# --- User code ---\n"
            f"{code}\n\n"
            "# --- Test code ---\n"
            f"{tests}\n"
        )

        try:
            with open(script_path, "w", encoding="utf-8") as f:
                f.write(script_content)
        except Exception as e:
            return f"CodeTestRunner error: failed to write temp script: {e!r}"

        # Run the script in a subprocess
        try:
            completed = subprocess.run(
                ["python", script_path],
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                timeout=timeout,
            )
            status = "success" if completed.returncode == 0 else "failure"
            exit_code = completed.returncode
            stdout = completed.stdout or ""
            stderr = completed.stderr or ""

            result = (
                f"Status: {status}\n"
                f"Exit code: {exit_code}\n\n"
                "[STDOUT]\n"
                f"{stdout}\n"
                "[STDERR]\n"
                f"{stderr}"
            )
            return result

        except subprocess.TimeoutExpired as e:
            stdout = e.stdout or ""
            stderr = e.stderr or ""
            return (
                "Status: timeout\n"
                f"Timeout after {timeout} seconds\n\n"
                "[STDOUT]\n"
                f"{stdout}\n"
                "[STDERR]\n"
                f"{stderr}"
            )
        except Exception as e:
            return f"CodeTestRunner internal error during execution: {e!r}"

    def _normalize_code_string(self, s: str) -> str:
        """
        LLM이 코드/테스트를 문자열 리터럴처럼 이스케이프해서 넘겼을 때,
        (\\n, \\" 등) 실제 코드로 되돌려준다.

        - unicode_escape 디코딩은:
          '\\n'  →  개행
          '\\"'  →  "
          "\\'"  →  '
          '\\t'  →  탭
          '\\\\' →  역슬래시
        - 원본에 이런 이스케이프가 아예 없다면 그대로 반환.
        """
        if not isinstance(s, str):
            return s

        # escape 시퀀스 흔적이 하나도 없으면 건드리지 않음
        if not self._escape_pattern.search(s):
            return s

        try:
            # 한 번 전체를 "파이썬 이스케이프"로 디코딩
            return bytes(s, "utf-8").decode("unicode_escape")
        except Exception:
            # 혹시 말도 안 되는 문자열이면 안전하게 원본 유지
            return s

    def get_tool_call_format(self):
        """
        Describe how the LLM should call this tool (OpenAI-style tool schema).
        """
        tool_call_format = {
            "type": "function",
            "function": {
                "name": "code/code_test_runner",
                "description": (
                    "Run Python code against test code in an isolated process "
                    "and return the test results. Useful for checking if "
                    "generated code passes unit tests."
                ),
                "parameters": {
                    "type": "object",
                    "properties": {
                        "code": {
                            "type": "string",
                            "description": (
                                "Python source code to be tested. Usually the "
                                "function or class implementation."
                            ),
                        },
                        "tests": {
                            "type": "string",
                            "description": (
                                "Python test code that imports or uses the "
                                "objects defined in `code`, typically with "
                                "assert statements."
                            ),
                        },
                        "timeout": {
                            "type": "number",
                            "description": (
                                "Optional timeout in seconds for running the "
                                "tests. Default is 5.0 seconds."
                            ),
                        },
                    },
                    "required": ["code", "tests"],
                },
            },
        }
        return tool_call_format
